language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
install:
  - pip install -r requirements.txt
  - python setup.py develop
  - pip install coveralls
  - rm -rf build
script:
  - export COVERAGE_PYTHON_VERSION=python-${TRAVIS_PYTHON_VERSION:0:1}
  - coverage run --source=thefuck,tests -m py.test -v
after_success: coveralls
