language: python
sudo: false
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
services:
  - docker
addons:
  apt:
    packages:
      - python-commandnotfound
      - python3-commandnotfound
install:
  - pip install -U pip
  - pip install -U coveralls
  - pip install -Ur requirements.txt
  - python setup.py develop
  - rm -rf build
script:
  - export COVERAGE_PYTHON_VERSION=python-${TRAVIS_PYTHON_VERSION:0:1}
  - export RUN_TESTS="coverage run --source=thefuck,tests -m py.test -v --capture=sys"
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then $RUN_TESTS --enable-functional; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then $RUN_TESTS; fi
after_success:
  - coveralls
